import copy

from pydantic import BaseModel


class TaskSingleOutput(BaseModel):
    """A task's output for a single sample.

    This is used for carrying additional information to the metrics: those which
    need it, can thus process it, while those which don't will ignore it, thus
    being retro-compatible with previous versions.

    """

    """The answer generated by the model.
    """
    answer: str | list[list[str] | str]

    """The (textual) context used by the model to generate the answer.
    """
    context: str | None = None

    """The number of tokens in the context, as calculated by the model's tokenizer.
    """
    context_tokens_count: int | None = None

    """How many images were used in the context.
    """
    num_images: int | None = None

    """Loglikelihood of the generated answer, if available.
    """
    loglikelihood: float | None = None

    """Perplexity of the generated answer, if available.
    """
    perplexity: float | None = None

    """Whether this is a dummy sample that should be skipped
    """
    is_dummy: bool = False

    def __str__(self) -> str:
        return self.answer  # type: ignore

    def strip(self) -> str:
        """Strip the answer of leading and trailing whitespace."""
        assert isinstance(self.answer, str), "Answer is not a string"
        return self.answer.strip()

    def __getitem__(self, idx: int) -> str | list[str]:
        assert isinstance(self.answer, list), "Answer is not a list"
        return self.answer[idx]

    def get(self, idx: int) -> "TaskSingleOutput":
        """Get a new TaskSingleOutput with the answer at the given index.

        Args:
        ----
            idx (int): The index of the answer to get.

        """
        assert isinstance(self.answer, list), "Answer is not a list"

        clone = copy.deepcopy(self)
        clone.answer = self.answer[idx]

        return clone
