from pydantic import BaseModel


class TaskSingleOutput(BaseModel):
    """A task's output for a single sample.

    This is used for carrying additional information to the metrics: those which
    need it, can thus process it, while those which don't will ignore it, thus
    being retro-compatible with previous versions.

    """

    """The answer generated by the model.
    """
    answer: str

    """The (textual) context used by the model to generate the answer.
    """
    context: str | None = None

    """The number of tokens in the context, as calculated by the model's tokenizer.
    """
    context_tokens_count: int | None = None

    """How many images were used in the context.
    """
    num_images: int | None = None

    def __str__(self) -> str:
        return self.answer

    def strip(self) -> str:
        """Strip the answer of leading and trailing whitespace."""
        return self.answer.strip()
